---
- name: Deploy Prometheus and Grafana
  hosts: grafana
  remote_user: ec2-user
  become: true

  tasks:
    - name: Install Prometheus
      shell: |
        mkdir /app
        cd /app
        wget https://github.com/prometheus/prometheus/releases/download/v2.45.3/prometheus-2.45.3.linux-amd64.tar.gz
        tar -xvf prometheus-2.45.3.linux-amd64.tar.gz
        mv prometheus-2.45.3.linux-amd64 prometheus-files
        useradd --no-create-home --shell /bin/false prometheus
        mkdir /etc/prometheus
        mkdir /var/lib/prometheus
        chown prometheus:prometheus /etc/prometheus
        chown prometheus:prometheus /var/lib/prometheus
        cp prometheus-files/prometheus /usr/local/bin/
        cp prometheus-files/promtool /usr/local/bin/
        chown prometheus:prometheus /usr/local/bin/prometheus
        chown prometheus:prometheus /usr/local/bin/promtool
        sudo cp -r prometheus-files/consoles /etc/prometheus
        cp -r prometheus-files/console_libraries /etc/prometheus
        chown -R prometheus:prometheus /etc/prometheus/consoles
        chown -R prometheus:prometheus /etc/prometheus/console_libraries
    - name: Configure Prometheus
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
    - name: Configure Prometheus
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
    - name: Daemon reload
      shell: |
        systemctl daemon-reload
        systemctl start prometheus
    - name: Import grafana key
      shell: |
        wget -q -O gpg.key https://rpm.grafana.com/gpg.key
        rpm --import gpg.key
    - name: create garfana repo
      template:
        src: grafana.repo.j2
        dest: /etc/yum.repos.d/grafana.repo
    - name: install grafana
      shell: |
        yum update -y
        yum install grafana-enterprise -y
    - name: Configure Grafana
      template:
        src: grafana.ini.j2
        dest: /etc/grafana/grafana.ini
    - name: Start Grafana
      shell: |
        systemctl daemon-reload
        systemctl start grafana-server
